Lang.prototype.pack.pt = {
    "token": {
        "Developers": "Desenvolvedores",
        "http://docs.jooycar.com": "http://docs.jooycar.com",
        "Contact": "Contato",
        "#contact-form": "#contact-form",

        "Meet": "Experiências de",
        "SmartCar": "automóveis conectados",
        "experiences for the new consumer": "para o novo consumidor",
        "Our products allow our clients to obtain real time data from vehicles and drivers while using Artificial Inteligence techniques in order to offer connected insurances and smart services with added value. Improving client fidelity, efficiency and new business for Insurance and Automotive companies.": "Nossa plataforma tecnológica permite obter dados em tempo real de carros e motoristas, acrescentando inteligência a eles para oferecer seguros conectados e serviços inteligentes de valor agregado. Gerando maior fidelidade, eficiência e novas oportunidades de negócios para as indústrias de seguros e automotiva.",
        "Try Demo": "Solicitar Demo",

        "Real Time Data Processing": "Processamento de dados em Tempo Real",
        "Insights With Contextual Cata": "Enriquecimento com dados contextuais",
        "Plug & Play Fast Integration": "Integração rápida Plug & Play",
        "Analytics & Machine Learning": "Analytics & Machine Learning",
        "Instant Access through API + SDK": "Acesso rápido através de API + SDK",
        "Multiple data Sources and Compatibilities": "Múltiplas Fontes de Dados e Compatibilidade",
    
        "Jooycar for insurance": "Jooycar for Insurance",
        "Our products allow Insurance Companies to create new connected insurance policies that generate superior digital experiences, creating value for the final consumer and enhancing the policyholder ́s experience and retention with the company.": "Nossa plataforma permite que as seguradoras criem novas apólices de seguro conectadas que geram experiências digitais superiores, criando valor para o consumidor final, aprimorando a experiência do segurado e sua permanência com a empresa.",
        "Better consumer insight": "Melhor percepção do consumidor",
        "Improve engagement": "Melhor engajamento",
        "Generate more accurate pricing": "Gere preços mais precisos",
        "A more predictable risk base": "Uma base de riscos mais previsível",
        "Variety of scores and client segmentation": "Variedade de pontuações e segmentação de clientes",
        "Jooycar for Fleets": "Jooycar for Fleets",
        "Our Jooycar solution is designed to address Fleet Safety and Fuel Efficiency requirements with a comprehensive and approach that is easy to set up. We seek to reduce the cost of operation and the impact of their business on the environment.": "Nossa solução Jooycar foi projetada para atender aos requisitos de Segurança de Frota e Eficiência de Combustível com uma abordagem abrangente e fácil de configurar. Procuramos reduzir o custo de operação e o impacto de seus negócios no meio ambiente.",
        "Latest Technology and Auto-Installable": "A mais nova tecnologia e Auto-instalável",
        "Real-time Vehicle information": "Informações de veículo em tempo real",
        "Greater Control over the fleet & Drivers": "Maior controle sobre a frota e motoristas",
        "Risk managment": "Gerenciamento de riscos",
        "Enhance the operation": "Melhore a operação",
        "Improve efficiency to lower costs": "Melhore a eficiência para reduzir custos",
        "Lower maintenance costs by Prevention Program": "Menores custos de manutenção pelo Programa de Prevenção",
        "Jooycar for Automotive": "Jooycar for Automotive",
        "A Real-time vehicle information means:": "Uma informação de veículo em tempo real significa:",
        "We strongly support disruptive innovation for car dealerships and roadside assistance companies in order to revolutionize the way in which they communicate with their customers and allow access to offer services according to the latest technology in the market.": "Apoiamos fortemente a inovação disruptiva para concessionárias e empresas de assistência rodoviária, a fim de revolucionar a maneira como eles se comunicam com seus clientes e permitir o acesso para oferecer serviços de acordo com a mais recente tecnologia do mercado.",
        "Enhance brand loyalty for vehicles": "Aumente a fidelidade à marcas para veículos",
        "Offer new consumer services": "Ofereça novos serviços ao consumidor",
        "Add new and powerful experiences to drivers": "Adicione novas e poderosas experiências aos motoristas",
        "Leverage vehicle and driving data to create new business models": "Alavancando veículos e gerando dados para criar novos modelos de negócios",
        "Act proactively to provide support the client in case of failures and breakdowns": "Atue proativamente para fornecer suporte ao cliente em casos de falhas e avarias",

        "THEY ARE TALKING ABOUT US": "ESTÃO FALANDO DE NÓS",
        "“Jooycar es pionera en Latinoamérica y está impulsando las polizas de auto conectado en nuestro país”": "“A Jooycar é pioneira na América Latina e está conduzindo as políticas de veículos conectados em nosso país”",
        "“After only three years, they’ve gained a strong reputation as one of the most innovative IoT products in the market”": "“Depois de apenas três anos, eles ganharam uma forte reputação como um dos produtos mais inovadores de IoT do mercado.”",
        "“Jooycar looks to enhance car-insurance industry”": "“A Jooycar procura melhorar a indústria de seguros de automóveis”",

        "Show More": "Mostrar Mais",
        "Show Less": "Mostrar Menos",
        
        "They are already using Jooycar:": "Eles já estão usando Jooycar:",

        "Team Jooycar": "Equipe Jooycar",
        "team.html": "team.html",
        "Career": "Trabalhe conosco",
        "https://www.getonbrd.com/companies/jooycar": "https://www.getonbrd.com/companies/jooycar",

        "mailto:contact@jooycar.com": "mailto:contacto@jooycar.com",
        "contact@jooycar.com": "contacto@jooycar.com",
        "http://www.jooycar.cl": "http://www.jooycar.cl",
        "Chile": "Chile",
        "http://www.jooycar.com.pe": "http://www.jooycar.com.pe",
        "Peru": "Perú",
        "http://www.jooycar.com.br": "http://www.jooycar.com.br",
        "Brazil": "Brasil",
        "http://www.jooycar.co": "http://www.jooycar.co",
        "Colombia": "Colombia",
        "http://www.jooycar.mx": "http://www.jooycar.mx",
        "Mexico": "México",
        "http://usa.jooycar.com": "http://usa.jooycar.com",
        "USA": "USA",

        "HQ: Santa Beatriz 100, office 604 Providencia,": "HQ: Santa Beatriz 100, escritório 604 - Providencia,",
        
        "Contact Us": "Contato",
        "If you would like to know more about our services": "Quer conhecer mais dos nossos serviços?",    
        "Company Name": "Nome da Empresa",
        "Your Name": "Seu Nome",
        "Email": "Email",
        "Message": "Mensagem",
        "Send": "Enviar",

        "Speeding for this area": "Excesso de velocidade",
        "102 mph": "140 km/h",
        "User Score": "Pontuação",
        "Trip in progress": "Viagem em andamento",
        "2:30 pm": "2:30 pm",
        "Apr 4": "Abr 4",
        "Hard turn": "Virada brusca",
        "16 mi Distance": "Distância 25 km",

        "Jooycar Team": "Time Jooycar",
        "Passionated experts in technology and innovation": "Especialistas apaixonados por tecnologia e inovação",
        "You": "Você"
    }
}