Lang.prototype.pack.pt = {
    "token": {
        "Developers": "Desarrolladores",
        "http://docs.jooycar.com": "http://docs.jooycar.com",
        "Contact": "Contacto",
        "#contact-form": "#contact-form",

        "Meet": "Experiencias de",
        "SmartCar": "automóviles conectados",
        "experiences for the new consumer": "para el nuevo consumidor",
        "Our products allow our clients to obtain real time data from vehicles and drivers while using Artificial Inteligence techniques in order to offer connected insurances and smart services with added value. Improving client fidelity, efficiency and new business for Insurance and Automotive companies.": "Nuestra plataforma tecnológica permite obtener datos en tiempo real provenientes de los automóviles y conductores agregando inteligencia a estos para ofrecer seguros conectados y servicios inteligentes de valor agregado. Generando mayor fidelidad, eficiencia y nuevas oportunidades de negocio para la industria de seguros y automotriz.",
        "Try Demo": "Solicitar Demo",

        "Real Time Data Processing": "Procesamiento de datos en Tiempo Real",
        "Insights With Contextual Cata": "Enriquecimiento con Data contextual",
        "Plug & Play Fast Integration": "Integración rápida Plug & Play",
        "Analytics & Machine Learning": "Analítica y Machine Learning",
        "Instant Access through API + SDK": "Acceso rápido a través de API + SDK",
        "Multiple data Sources and Compatibilities": "Multiples Fuentes de Datos y Compatibilidad",
    
        "Jooycar for insurance": "Jooycar for insurance",
            "Our products allow Insurance Companies to create new connected insurance policies that generate superior digital experiences, creating value for the final consumer and enhancing the policyholder ́s experience and retention with the company.": "",
            "Better consumer insight": "",
            "Improve engagement": "",
            "Generate more accurate pricing": "",
            "A more predictable risk base": "",
            "Variety of scores and client segmentation": "",
            "Jooycar for Fleets": "",
            "Our Jooycar solution is designed to address Fleet Safety and Fuel Efficiency requirements with a comprehensive and approach that is easy to set up. We seek to reduce the cost of operation and the impact of their business on the environment.": "",
            "Latest Technology and Auto-Installable": "",
            "Real-time Vehicle information": "",
            "Greater Control over the fleet & Drivers": "",
            "Risk managment": "",
            "Enhance the operation": "",
            "Improve efficiency to lower costs": "",
            "Lower maintenance costs by Prevention Program": "",
            "Jooycar for Automotive": "",
            "A Real-time vehicle information means:": "",
            "We strongly support disruptive innovation for car dealerships and roadside assistance companies in order to revolutionize the way in which they communicate with their customers and allow access to offer services according to the latest technology in the market.": "",
            "Enhance brand loyalty for vehicles": "",
            "Offer new consumer services": "",
            "Add new and powerful experiences to drivers": "",
            "Leverage vehicle and driving data to create new business models": "",
            "Act proactively to provide support the client in case of failures and breakdowns": "",

        "THEY ARE TALKING ABOUT US": "HABLAN DE NOSOTROS",
        "“Jooycar es pionera en Latinoamérica y está impulsando las polizas de auto conectado en nuestro país”": "“Jooycar es pionera en Latinoamérica y está impulsando las polizas de auto conectado en nuestro país”",
        "“After only three years, they’ve gained a strong reputation as one of the most innovative IoT products in the market”": "“After only three years, they’ve gained a strong reputation as one of the most innovative IoT products in the market”",
        "“Jooycar looks to enhance car-insurance industry”": "“Jooycar looks to enhance car-insurance industry”",

        "Show More": "Mostrar Más",
        "Show Less": "Mostrar Menos",
        
        "They are already using Jooycar:": "Ellos ya están usando Jooycar:",

        "Team Jooycar": "Equipo Jooycar",
        "team.html": "team.html",
        "Career": "Trabaja con nosotros",
        "https://www.getonbrd.com/companies/jooycar": "https://www.getonbrd.com/companies/jooycar",

        "mailto:contact@jooycar.com": "mailto:contacto@jooycar.com",
        "contact@jooycar.com": "contacto@jooycar.com",
        "http://www.jooycar.cl": "http://www.jooycar.cl",
        "Chile": "Chile",
        "http://www.jooycar.com.pe": "http://www.jooycar.com.pe",
        "Peru": "Perú",
        "http://www.jooycar.com.br": "http://www.jooycar.com.br",
        "Brazil": "Brasil",
        "http://www.jooycar.co": "http://www.jooycar.co",
        "Colombia": "Colombia",
        "http://www.jooycar.mx": "http://www.jooycar.mx",
        "Mexico": "México",
        "http://usa.jooycar.com": "http://usa.jooycar.com",
        "USA": "USA",

        "HQ: Santa Beatriz 100, office 604 Providencia,": "HQ: Santa Beatriz 100, office 604 Providencia,",
        
        "Contact Us": "Contáctanos",
        "If you would like to know more about our services": "Si quieres conocer más de nuestros servicios",    
        "Company Name": "Nombre de la Empresa",
        "Your Name": "Tu Nombre",
        "Email": "Email",
        "Message": "Mensaje",
        "Send": "Enviar",

        "Speeding for this area": "Exceso de velocidad",
        "102 mph": "140 km/h",
        "User Score": "Puntaje",
        "Trip in progress": "Viaje en curso",
        "2:30 pm": "2:30 pm",
        "Apr 4": "Abr 4",
        "Hard turn": "Giro brusco",
        "16 mi Distance": "Distancia 25 km",

        "Jooycar Team": "Jooycar Team",
        "Passionated experts in technology and innovation": "Apasionados y expertos en tecnología e innovación",
        "You": "Tú"
    },

}
